load("//build_tools:feature_macro.bzl", "feature_macro")

feature_macro(
    name = "Selection",
    srcs = glob(["**/*.swift"]),
    deps = [
        "//Modules/NetworkingInterface/Sources:NetworkingInterface",
        "//Modules/SelectionInterface/Sources:SelectionInterface",
        "//Modules/SummaryInterface/Sources:SummaryInterface",
        "//Modules/RouterService/Sources:RouterService",
    ],
) 