load("//build_tools:feature_macro.bzl", "feature_macro")

feature_macro(
    name = "RootRIB",
    srcs = glob(["**/*.swift"]),
    deps = [
        "//Modules/ListInterface/Sources:ListInterface",
    ],
) 