load("//build_tools:feature_macro.bzl", "feature_macro")

feature_macro(
    name = "SelectionRIB",
    srcs = glob(["**/*.swift"]),
    deps = [
        # "//Modules/RIBs:RIBs",
        "//Modules/SummaryInterface/Sources:SummaryInterface",
        "//Modules/Summary/Sources:Summary",
    ],
) 