load("//build_tools:feature_macro.bzl", "feature_macro")

feature_macro(
    name = "SelectionRIB",
    srcs = glob(["**/*.swift"]),
    deps = [
        # "//Modules/RIBs:RIBs",
        "//Modules/DetailsInterface/Sources:DetailsInterface",
        "//Modules/Details/Sources:Details",
    ],
) 