load("//build_tools:feature_macro.bzl", "feature_macro")

feature_macro(
    name = "Monolith",
    srcs = glob(["*.swift"]),
    data = glob(
        ["Resources/**"],
        exclude = ["**/.DS_Store"],
    ),
    deps = [],
)