load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ListInterface",
    module_name = "ListInterface",
    deps = [
        "//Modules/RouterService/Sources:RouterService",
    ],
    srcs = glob(["**/*.swift"]),
    visibility = ["//visibility:public"],
) 