load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Networking",
    srcs = glob(["**/*.swift"]),
    module_name = "Networking",
    visibility = ["//visibility:public"],
    deps = []
)